version: '3.7'
services:
  odoo:
    volumes:
      - ./odoo/config/odoo.conf:/etc/odoo/odoo.conf

  nginx:
    container_name: odoo-nginx
    image: nginx:latest
    restart: unless-stopped
    command: /bin/sh -c "while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g 'daemon off;'"
    ports:
        - 80:80
        - 443:443
    volumes:
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/site.com.conf:/etc/nginx/sites-enabled/site.com.conf
        - ./nginx/site.com.conf:/etc/nginx/sites-enabled/site.com.conf
        - ./certbot/conf:/etc/letsencrypt/
        - ./certbot/www:/var/www/html
    depends_on:
      - odoo

  certbot:
    container_name: odoo-certbot
    image: certbot/certbot:latest
    restart: unless-stopped
    entrypoint: /bin/sh -c "trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;"
    volumes:
        - ./certbot/conf:/etc/letsencrypt/
        - ./certbot/www:/var/www/html

  db:
    volumes:
      - ./postgres/pgdata:/var/lib/postgresql/data/pgdata