version: '3.7'
services:
  odoo:
    image: odoo:14.0
    container_name: odoo-app
    build:
      context: ./odoo
    restart: always
    environment:
      - HOST=odoo-db
    command:
      --without-demo all
    ports:
      - 8069:8069
      - 8072:8072
    volumes:
      - ./odoo/sessions:/var/lib/odoo/sessions:rw
      - ./odoo/filestore:/var/lib/odoo/filestore:rw
      - ./odoo/addons:/mnt/extra-addons
    depends_on:
      - db

  db:
    image: postgres:10
    container_name: odoo-db
    build:
      context: ./postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres/backups:/BACKUP:rw
      - ./postgres/pgdata:/var/lib/postgresql/data/pgdata:rw

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: odoo-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: email@example.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin4pass
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 8084:80
    volumes:
      - ./pgadmin4:/var/lib/pgadmin
    depends_on:
      - db